### PR TITLE
Working on adding in some new cheeses

### PR DESCRIPTION
**Pull request by Sunconure11**
Because why not? Also implemented some compatibility measures. Do not merge yet, I cannot run a game without a weird crash relating to the apple module.

https://pastebin.com/DAubk1Hp

This also likely needs some new textures

### CODE REVIEW

**Comment by Avatair** [comment]
I added fallback recipes in  https://github.com/GrowthcraftCE/Growthcraft-1.12/pull/90 . Null items are handled as wilcards there. It seems that the version you are using is somehow incompatible.

**Comment by Avatair** [comment]
Or maybe also I messed up with NonNull annotations and didn't notice it on my Java version. In this case it is safe to remove these annotation for item keys in the recipe registry for fermentation and brewing.

**Comment by Sunconure11** [comment]
I guess it's safe to merge then, provided you give them some testing, since I was unable to test them due to this.

**Comment by Alatyami** [comment]
Missing some textures when loading, but other than that, looks good.

**Comment by Deshiba** [comment]
Put it up on the server for a test cycle? Or is other stuff coming?

**Comment by Alatyami** [comment]
It'll be in the 4.0.4.500 release.

**Comment by Alatyami** [comment]
@sun, which version of java are you using?

**Comment by sun** [comment]
@Alatyami meant @Sunconure11, it seems.

**Comment by Sunconure11** [comment]
Screenshot 2019-04-02 09 41 43

**Pull request merged**
